version: '3.8'

services:
  unduck:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL:-https://unduck.thismodern.dev}
    image: adversarialink/unduck:latest
    ports:
      - "3099:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3